version: 2
jobs:
#  build:
#    machine:
#      image: circleci/classic:edge
#    steps:
#      - checkout
#      - run:
#          name: docker-compose up
#          command: docker-compose up -d
#      - run:
#          name: sleep for launch db to migrate at Django
#          command: sleep 10
#      - run:
#          name: migrate
#          command: docker-compose run python ./manage.py migrate
#      - run:
#          name: test
#          command: docker-compose run python ./manage.py test
#      - run:
#          name: docker-compose down
#          command: docker-compose down
    build:
      machine:
        image: circleci/classic:edge
      steps:
        - checkout
        - add_ssh_keys:
        - run: ssh ${USER_NAME}@${HOST_NAME} 'cd todoList && before=`cat ./python/* | md5sum` && git pull && after=`cat ./python/* | md5sum` && if [ "$before" != "$after" ]; then docker-compose down && docker-compose up -d --build;fi && docker-compose run python ./manage.py migrate'

#workflows:
#  version: 2
#  build_and_deploy:
#    jobs:
#      - build
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master