# Environment variables
# - HOST_NAME
# - USER_NAME

version: 2
jobs:
#  build:
#    machine:
#      image: circleci/classic:edge
#    steps:
#      - checkout
#      - run:
#          name: docker-compose up
#          command: docker-compose up -d
#      - run:
#          name: sleep for launch db to migrate at Django
#          command: sleep 10
#      - run:
#          name: migrate
#          command: docker-compose run python ./manage.py migrate
#      - run:
#          name: test
#          command: docker-compose run python ./manage.py test
#      - run:
#          name: docker-compose down
#          command: docker-compose down
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd todoList && pwd'
#      - run: exit
#          fingerprints:
#            - '9c:19:4d:57:c7:16:0f:a2:8a:3e:88:50:15:09:c2:85'

#            - run:
#                name: Start ssh-keyscan
#                command: ssh ${USER_NAME}@${HOST_NAME} -p 50022
#
#            - deploy:
#                name: Start master deploy
#                command: exit
#workflows:
#  version: 2
#  build_and_deploy:
#    jobs:
#      - build
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master